//! audio.rs — PIO I²S master-mode capture + RMS computation
//!
//! The SPH0645LM4H sends 24-bit samples left-justified inside 32-bit words.
//! The mic is an I2S slave — the Pico must generate BCLK and WS clocks.
//!
//! PIO program: master-mode — generates BCLK + WS via side-set, reads DOUT.
//! BCLK=GP0, LRCL=GP1 (must be consecutive for side-set), DOUT=GP2.
//!
//! Sample rate: 16 kHz  →  window = 1600 samples = 100 ms

use defmt::*;
use embassy_rp::{
    peripherals::{DMA_CH0, PIO0},
    pio::{Config, Direction, FifoJoin, Pio, ShiftConfig, ShiftDirection},
};
use fixed::traits::ToFixed;
use libm::log10f;

use crate::DB_CHANNEL;

const SAMPLE_RATE:    u32 = 16_000;
const WINDOW_SAMPLES: usize = 1_600;   // 100 ms at 16 kHz
const FULL_SCALE_24:  f32 = 8_388_608.0; // 2^23

// 2nd-order Butterworth high-pass filter at 200 Hz (fs = 16 kHz)
// Removes DC, 50/60 Hz mains hum, and low-frequency power supply noise.
// -12 dB/octave rolloff → ~24 dB attenuation at 50 Hz.
// Baby crying (250+ Hz) and speech pass through with minimal loss.
// Coefficients pre-computed and normalized by a0.
const HPF_B0: f32 =  0.9460;
const HPF_B1: f32 = -1.8920;
const HPF_B2: f32 =  0.9460;
const HPF_A1: f32 = -1.8890;
const HPF_A2: f32 =  0.8949;

#[embassy_executor::task]
pub async fn audio_task(
    pio:      PIO0,
    _dma_ch:  DMA_CH0,
    bclk_pin: embassy_rp::peripherals::PIN_0,
    lrcl_pin: embassy_rp::peripherals::PIN_1,
    data_pin: embassy_rp::peripherals::PIN_2,
) {
    info!("[audio] task started");

    let Pio { mut common, mut sm0, .. } = Pio::new(pio, crate::Irqs);

    // PIO I²S master-mode receive program
    // Side-set 2 bits: bit0 = BCLK, bit1 = WS/LRCL
    // Generates BCLK + WS clocks while reading DOUT
    // Each bit takes 2 PIO instructions → BCLK toggles every instruction via side-set
    // WS transitions on the last bit of each channel (standard I2S timing)
    let prog = pio_proc::pio_asm!(
        ".side_set 2",
        //                                    ; side 0bWB (W=word select, B=bit clock)
        "    set x, 30          side 0b00",   // X=30: loop 31 + 1 final = 32 bits
        "left_data:",
        "    in pins, 1         side 0b01",   // Read DOUT, raise BCLK
        "    jmp x-- left_data  side 0b00",   // Lower BCLK, loop
        "    in pins, 1         side 0b11",   // Last left bit: raise BCLK + WS high
        "    set x, 30          side 0b10",   // Reset counter, lower BCLK, WS stays high
        "right_data:",
        "    in pins, 1         side 0b11",   // Read DOUT, raise BCLK
        "    jmp x-- right_data side 0b10",   // Lower BCLK, loop
        "    in pins, 1         side 0b01",   // Last right bit: raise BCLK + WS low
        //                                    ; wraps to set x, 30 side 0b00
    );

    let mut cfg = Config::default();

    // Side-set pins: BCLK (GP0) and WS (GP1) — must be consecutive
    let bclk_pin = common.make_pio_pin(bclk_pin);
    let lrcl_pin = common.make_pio_pin(lrcl_pin);
    cfg.use_program(&common.load_program(&prog.program), &[&bclk_pin, &lrcl_pin]);

    // Input pin: GP2 (DOUT from mic)
    let data_pin = common.make_pio_pin(data_pin);
    cfg.set_in_pins(&[&data_pin]);

    // 32-bit shift, MSB first, auto-push at 32 bits
    cfg.shift_in = ShiftConfig {
        auto_fill: true,
        threshold: 32,
        direction: ShiftDirection::Left,
    };
    cfg.fifo_join = FifoJoin::RxOnly;

    // Clock divider for 16 kHz sample rate:
    // PIO freq = sample_rate × bits × channels × 2 (instructions per bit)
    //          = 16000 × 32 × 2 × 2 = 2,048,000 Hz
    // RP2350 sys clock = 150 MHz → divider = 150M / 2.048M ≈ 73.24
    // Using 73 gives BCLK ≈ 1.027 MHz (within SPH0645's 1.024–4.096 MHz range)
    cfg.clock_divider = 73u8.to_fixed();

    sm0.set_config(&cfg);

    // BCLK and WS are outputs (generated by PIO), DOUT is input
    sm0.set_pin_dirs(Direction::Out, &[&bclk_pin, &lrcl_pin]);
    sm0.set_pin_dirs(Direction::In, &[&data_pin]);
    sm0.set_enable(true);

    info!("[audio] PIO I2S master @ {}Hz, div=73", SAMPLE_RATE);

    // ── HPF state (2nd-order biquad) ─────────────────────────────────────
    let mut hpf_x1: f32 = 0.0;
    let mut hpf_x2: f32 = 0.0;
    let mut hpf_y1: f32 = 0.0;
    let mut hpf_y2: f32 = 0.0;

    // Warmup: 200ms — mic PDM stabilization + HPF settling
    for _ in 0..(SAMPLE_RATE as usize / 5) {
        let raw: u32 = sm0.rx().wait_pull().await;
        let _right: u32 = sm0.rx().wait_pull().await;
        let sample = ((raw as i32) >> 8) as f32;
        let y = HPF_B0 * sample + HPF_B1 * hpf_x1 + HPF_B2 * hpf_x2
              - HPF_A1 * hpf_y1 - HPF_A2 * hpf_y2;
        hpf_x2 = hpf_x1;
        hpf_x1 = sample;
        hpf_y2 = hpf_y1;
        hpf_y1 = y;
    }
    info!("[audio] Mic warmup complete");

    // ── Sample loop ───────────────────────────────────────────────────────
    // SPH0645 with SEL=GND outputs on LEFT channel only.
    // PIO pushes stereo pairs: left (data) then right (zeros). Read both, discard right.
    let mut buf  = [0f32; WINDOW_SAMPLES];
    let mut idx  = 0usize;
    let mut smoothed: f32 = -96.0;
    const EMA_ATTACK: f32 = 0.3;  // Fast rise — catches loud events quickly
    const EMA_DECAY:  f32 = 0.08; // Slow fall — stable reading during quiet

    loop {
        let raw: u32 = sm0.rx().wait_pull().await;     // Left channel (has data)
        let _right: u32 = sm0.rx().wait_pull().await;  // Right channel (discard)

        // SPH0645: 24-bit data left-justified in 32-bit word; right-shift 8 for signed 24-bit
        let sample = ((raw as i32) >> 8) as f32;

        // 2nd-order Butterworth HPF at 200 Hz (replaces DC blocker)
        // Removes DC offset, 50/60 Hz mains hum, and power supply noise
        let filtered = HPF_B0 * sample + HPF_B1 * hpf_x1 + HPF_B2 * hpf_x2
                     - HPF_A1 * hpf_y1 - HPF_A2 * hpf_y2;
        hpf_x2 = hpf_x1;
        hpf_x1 = sample;
        hpf_y2 = hpf_y1;
        hpf_y1 = filtered;

        buf[idx] = filtered;
        idx += 1;

        if idx >= WINDOW_SAMPLES {
            idx = 0;
            let db = compute_db(&buf);
            let alpha = if db > smoothed { EMA_ATTACK } else { EMA_DECAY };
            smoothed = alpha * db + (1.0 - alpha) * smoothed;
            if DB_CHANNEL.try_send(smoothed).is_err() {
                dev_log!(crate::dev_log::LogCat::Audio, crate::dev_log::LogLevel::Warn,
                    "DB_CHANNEL full, dropped db={:.1}", smoothed);
            }
        }
    }
}

fn compute_db(samples: &[f32]) -> f32 {
    if samples.is_empty() {
        return -96.0;
    }
    let mut sum: f32 = 0.0;
    for &s in samples {
        sum += s * s;
    }
    let rms = libm::sqrtf(sum / samples.len() as f32);
    if rms < 1.0 {
        return -96.0;
    }
    20.0 * log10f(rms / FULL_SCALE_24)
}
